# Generated by Django 4.0.1 on 2022-01-29 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgdapi', '0002_contrasena_reinicio_estado_alter_usuario_avatar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpeta',
            old_name='fecha_creacion',
            new_name='fechaCreacion',
        ),
        migrations.RenameField(
            model_name='carpeta',
            old_name='tipo_carpeta',
            new_name='tipoCarpeta',
        ),
        migrations.RenameField(
            model_name='contrasena_reinicio',
            old_name='fecha_cambio',
            new_name='fechaCambio',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='fecha_subida',
            new_name='fechaSubida',
        ),
        migrations.RenameField(
            model_name='documentoocr',
            old_name='fecha_registro',
            new_name='fechaRegistro',
        ),
        migrations.RenameField(
            model_name='propiedaddocumento',
            old_name='responsable_doc',
            new_name='responsableDoc',
        ),
        migrations.RenameField(
            model_name='subcarpeta',
            old_name='fecha_creacion',
            new_name='fechaCreacion',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='fecha_actualizacion',
            new_name='fechaActualizacion',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='fecha_creacion',
            new_name='fechaCreacion',
        ),
    ]
