# Generated by Django 4.0.1 on 2022-01-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdapi', '0003_rename_fecha_creacion_carpeta_fechacreacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Correo electronico'),
        ),
    ]
