# Generated by Django 4.0.1 on 2022-01-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdapi', '0005_alter_contrasena_reinicio_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrasena_reinicio',
            name='correo',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Correo usuario'),
        ),
        migrations.AlterField(
            model_name='contrasena_reinicio',
            name='token',
            field=models.CharField(max_length=255, unique=True, verbose_name='token validador'),
        ),
    ]
