# Generated by Django 4.0.1 on 2022-01-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdapi', '0006_alter_contrasena_reinicio_correo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contrasena',
            new_name='password',
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='contrasena_reinicio',
            name='token',
            field=models.CharField(max_length=40, unique=True, verbose_name='token validador'),
        ),
    ]
