# Generated by Django 4.0.1 on 2022-02-26 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sgdapi', '0009_documento_documento_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalContrasena_reinicio',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('correo', models.EmailField(db_index=True, max_length=255, verbose_name='Correo usuario')),
                ('token', models.CharField(db_index=True, max_length=40, verbose_name='token validador')),
                ('fechaCambio', models.DateField(blank=True, editable=False, verbose_name='Fecha de Cambio')),
                ('estado', models.SmallIntegerField(default=1, null=True, verbose_name='Estado del token')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Contrasena_reinicio',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
