# Generated by Django 4.0.1 on 2022-02-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdapi', '0011_remove_documento_carpeta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='nombreDocumento',
            field=models.CharField(max_length=100, verbose_name='Nombres del documento'),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='nombreDocumento',
            field=models.CharField(max_length=100, verbose_name='Nombres del documento'),
        ),
    ]
