# Generated by Django 4.0.1 on 2022-02-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdapi', '0014_alter_documento_documento_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='contrasena_reinicio',
            name='fechaCambio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fechaSubida',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subidas'),
        ),
        migrations.AlterField(
            model_name='documentoocr',
            name='fechaRegistro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro de converciones'),
        ),
        migrations.AlterField(
            model_name='historicalcarpeta',
            name='fechaCreacion',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='historicalcontrasena_reinicio',
            name='fechaCambio',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Cambio'),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='fechaSubida',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de subidas'),
        ),
        migrations.AlterField(
            model_name='historicaldocumentoocr',
            name='fechaRegistro',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de registro de converciones'),
        ),
        migrations.AlterField(
            model_name='historicalsubcarpeta',
            name='fechaCreacion',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creaciones'),
        ),
        migrations.AlterField(
            model_name='subcarpeta',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de creaciones'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaActualizacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Creacion'),
        ),
    ]
