# Generated by Django 4.0.1 on 2022-02-12 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sgdapi', '0015_alter_carpeta_fechacreacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=6, verbose_name='Sulg')),
                ('nombreDocumento', models.CharField(max_length=100, verbose_name='Nombres del documento')),
                ('contenidoOCR', models.TextField(verbose_name='Contenidos del documento')),
                ('documento_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo del documento')),
                ('extension', models.CharField(blank=True, max_length=10, null=True, verbose_name='Extension de los archivos subidos')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='FileInFolder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=6, unique=True, verbose_name='Slug')),
                ('fechaCreacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
                ('fechaUpdate', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgdapi.file')),
            ],
            options={
                'verbose_name': 'File en folder',
                'verbose_name_plural': 'Files en folders',
            },
        ),
        migrations.CreateModel(
            name='FileTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRegistro', models.DateTimeField(auto_now=True, verbose_name='Fecha del registro')),
                ('fechaUpdate', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del registro')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgdapi.file')),
            ],
            options={
                'verbose_name': 'File Tag',
                'verbose_name_plural': 'File Tags',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=6, unique=True, verbose_name='Slug')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre del folder')),
                ('fechaCreacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
                ('fechaUpdate', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
            },
        ),
        migrations.CreateModel(
            name='FolderInFolder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=6, unique=True, verbose_name='Slug')),
                ('child_folder_name', models.CharField(max_length=45, verbose_name='Nombre del folder Hijo')),
                ('fechaCreacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
                ('fechaUpdate', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion')),
                ('child_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpeta_hija', to='sgdapi.folder')),
                ('parent_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpeta_padre', to='sgdapi.folder')),
            ],
            options={
                'verbose_name': 'Folder en folder',
                'verbose_name_plural': 'Folder en folders',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFile',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('slug', models.CharField(max_length=6, verbose_name='Sulg')),
                ('nombreDocumento', models.CharField(max_length=100, verbose_name='Nombres del documento')),
                ('contenidoOCR', models.TextField(verbose_name='Contenidos del documento')),
                ('documento_file', models.TextField(blank=True, max_length=100, null=True, verbose_name='Archivo del documento')),
                ('extension', models.CharField(blank=True, max_length=10, null=True, verbose_name='Extension de los archivos subidos')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical File',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFileInFolder',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('slug', models.CharField(db_index=True, max_length=6, verbose_name='Slug')),
                ('fechaCreacion', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('fechaUpdate', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualizacion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('file', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sgdapi.file')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_folder', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sgdapi.folder')),
            ],
            options={
                'verbose_name': 'historical File en folder',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFileTag',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha del registro')),
                ('fechaUpdate', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha del registro')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('file', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sgdapi.file')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical File Tag',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFolder',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('slug', models.CharField(db_index=True, max_length=6, verbose_name='Slug')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre del folder')),
                ('fechaCreacion', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('fechaUpdate', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualizacion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Folder',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFolderInFolder',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('slug', models.CharField(db_index=True, max_length=6, verbose_name='Slug')),
                ('child_folder_name', models.CharField(max_length=45, verbose_name='Nombre del folder Hijo')),
                ('fechaCreacion', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('fechaUpdate', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualizacion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('child_folder', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sgdapi.folder')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_folder', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sgdapi.folder')),
            ],
            options={
                'verbose_name': 'historical Folder en folder',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTag',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('tagName', models.CharField(db_index=True, max_length=50, verbose_name='Nombre del tag')),
                ('fechaRegistro', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha del registro')),
                ('fechaUpdate', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha del registro')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tag',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUnidadArea',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('nombreUnidad', models.CharField(db_index=True, max_length=100, verbose_name='Nombre del unidad')),
                ('fechaRegistro', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha del registro')),
                ('fechaUpdate', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha del registro')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('file', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sgdapi.file')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Unidad Area',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tagName', models.CharField(max_length=50, unique=True, verbose_name='Nombre del tag')),
                ('fechaRegistro', models.DateTimeField(auto_now=True, verbose_name='Fecha del registro')),
                ('fechaUpdate', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del registro')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='UnidadArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUnidad', models.CharField(max_length=100, unique=True, verbose_name='Nombre del unidad')),
                ('fechaRegistro', models.DateTimeField(auto_now=True, verbose_name='Fecha del registro')),
                ('fechaUpdate', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del registro')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgdapi.file')),
            ],
            options={
                'verbose_name': 'Unidad Area',
                'verbose_name_plural': 'Unidad Areas',
            },
        ),
        migrations.RemoveField(
            model_name='carpeta',
            name='subCarpeta',
        ),
        migrations.RemoveField(
            model_name='carpeta',
            name='tipoCarpeta',
        ),
        migrations.RemoveField(
            model_name='documentoocr',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='historicalareadocumento',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcarpeta',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcarpeta',
            name='subCarpeta',
        ),
        migrations.RemoveField(
            model_name='historicalcarpeta',
            name='tipoCarpeta',
        ),
        migrations.RemoveField(
            model_name='historicaldocumento',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentoocr',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentoocr',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpropiedaddocumento',
            name='areaDocumento',
        ),
        migrations.RemoveField(
            model_name='historicalpropiedaddocumento',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpropiedaddocumento',
            name='unidadDcumento',
        ),
        migrations.RemoveField(
            model_name='historicalsubcarpeta',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltipo_carpeta',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltipogestion',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalunidaddocumento',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='propiedaddocumento',
            name='areaDocumento',
        ),
        migrations.RemoveField(
            model_name='propiedaddocumento',
            name='unidadDcumento',
        ),
        migrations.DeleteModel(
            name='TipoGestion',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='AreaDocumento',
        ),
        migrations.DeleteModel(
            name='Carpeta',
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.DeleteModel(
            name='DocumentoOcr',
        ),
        migrations.DeleteModel(
            name='HistoricalAreaDocumento',
        ),
        migrations.DeleteModel(
            name='HistoricalCarpeta',
        ),
        migrations.DeleteModel(
            name='HistoricalDocumento',
        ),
        migrations.DeleteModel(
            name='HistoricalDocumentoOcr',
        ),
        migrations.DeleteModel(
            name='HistoricalPropiedadDocumento',
        ),
        migrations.DeleteModel(
            name='HistoricalSubCarpeta',
        ),
        migrations.DeleteModel(
            name='HistoricalTipo_carpeta',
        ),
        migrations.DeleteModel(
            name='HistoricalTipoGestion',
        ),
        migrations.DeleteModel(
            name='HistoricalUnidadDocumento',
        ),
        migrations.DeleteModel(
            name='PropiedadDocumento',
        ),
        migrations.DeleteModel(
            name='SubCarpeta',
        ),
        migrations.DeleteModel(
            name='Tipo_carpeta',
        ),
        migrations.DeleteModel(
            name='UnidadDocumento',
        ),
        migrations.AddField(
            model_name='historicalfiletag',
            name='tag',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sgdapi.tag'),
        ),
        migrations.AddField(
            model_name='filetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgdapi.tag'),
        ),
        migrations.AddField(
            model_name='fileinfolder',
            name='parent_folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgdapi.folder'),
        ),
    ]
