# Generated by Django 4.0.1 on 2022-02-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdapi', '0016_file_fileinfolder_filetag_folder_folderinfolder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='nombre',
            field=models.CharField(max_length=45, unique=True, verbose_name='Nombre del folder'),
        ),
        migrations.AlterField(
            model_name='historicalfolder',
            name='nombre',
            field=models.CharField(db_index=True, max_length=45, verbose_name='Nombre del folder'),
        ),
    ]
