# Generated by Django 4.0.1 on 2022-02-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdapi', '0017_alter_folder_nombre_alter_historicalfolder_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='nombre',
            field=models.CharField(max_length=45, verbose_name='Nombre del folder'),
        ),
        migrations.AlterField(
            model_name='folderinfolder',
            name='child_folder_name',
            field=models.CharField(max_length=45, unique=True, verbose_name='Nombre del folder Hijo'),
        ),
        migrations.AlterField(
            model_name='historicalfolder',
            name='nombre',
            field=models.CharField(max_length=45, verbose_name='Nombre del folder'),
        ),
        migrations.AlterField(
            model_name='historicalfolderinfolder',
            name='child_folder_name',
            field=models.CharField(db_index=True, max_length=45, verbose_name='Nombre del folder Hijo'),
        ),
    ]
