# Generated by Django 4.0.1 on 2022-02-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdapi', '0018_alter_folder_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderinfolder',
            name='child_folder_name',
            field=models.CharField(max_length=45, verbose_name='Nombre del folder Hijo'),
        ),
        migrations.AlterField(
            model_name='historicalfolderinfolder',
            name='child_folder_name',
            field=models.CharField(max_length=45, verbose_name='Nombre del folder Hijo'),
        ),
    ]
