# Generated by Django 4.0.1 on 2022-02-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='image',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='historicaluser',
            old_name='email',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='historicaluser',
            old_name='username',
            new_name='nombreUsuario',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='nombreUsuario',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='estado',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Estado del usuario'),
        ),
        migrations.AddField(
            model_name='user',
            name='estado',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Estado del usuario'),
        ),
    ]
