# Generated by Django 4.0.1 on 2022-02-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_historicaluser_nombreusuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='nombreUsuario',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombreUsuario',
            field=models.CharField(max_length=255, unique=True, verbose_name='Usuario'),
        ),
    ]
