# Generated by Django 4.0.1 on 2022-02-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_historicaluser_nombreusuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='avatars/', verbose_name='Imagen de perfil'),
        ),
    ]
